# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165PVlO2e3PZh2-l5F8yaGxBEO_daZ1Y5
"""

import pandas as pd

import numpy as np

d = {
    'A': [1,2, np.nan],
    'B': [5, np.nan, np.nan],
    'C': [1,2,3]
}

df = pd.DataFrame(d)

df

df.dropna()

df.dropna(axis = 0)

df.dropna(axis = 1)

df

df.fillna(value = 'Filling Value')

df = pd.DataFrame(d)

a = df['A'].fillna(value = df['A'].mean())

df

a

df

df['A'].fillna(value = df['A'].mean())

df

df.fillna??

df['A'].fillna(value = df['A'].mean(),inplace = True)

df

data = {
    'Company':['Google','Google','MSFT','FB','FB','IBM'],
    'Person': ['Sam','Nihad','Any','Van','Rakib','Ovi'],
    'Sales': [200, 120, 340, 124, 243, 350]
}

df = pd.DataFrame(data)

df

byComp = df.groupby('Company')

byComp.mean(numeric_only = True)

byComp.sum()

df



byComp.std(numeric_only = True)

df.groupby('Company').count()

df

df.groupby('Company').describe()

df1 = pd.DataFrame(np.random.randint(1, 20, size = (4, 3)),[1,2,3,4], ['w', 'x', 'y'])

df2 = pd.DataFrame(np.random.randint(20,40, size = (4, 3)), [5,6,7,8], ['W', 'X', 'Y'])

df3 = pd.DataFrame(np.random.randint(40,60, size = (4, 3)), [9,10,11,12], ['W', 'X', 'Y'])

df1

df2

df3

frame = [df1, df2, df3]

pd.concat(frame)

pd.concat(frame, axis = 1)

left = {
    'key':['k0','k1','k2','k3'],
    'A':[10,20,30,40],
    'B':[1,2,3,4]
}

right = {
    'key':['k0','k1','k2','k3'],
    'C':[100,200,300,400],
    'D':[11,12,13,14]
    }

left = pd.DataFrame(left)

right = pd.DataFrame(right)

left

right

pd.merge(left, right, on='key')

pd.merge??

left ={
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2']
}

right = {
    'C':['C0','C2','C3'],
    'D':['D0','D2','D3']

}

left = pd.DataFrame(left, index = ['K0','k1','k2'])

right = pd.DataFrame(right,index = ['K0','K2','K3'])

left

right

left.join(right, how = 'inner')

left.join??

df = pd.DataFrame({
    'col1':[444,555,666,444],
    'col2':[1,2,3,4],
    'col3':['abc','def','ghi','xyz']
})

df

df['col1'].unique()

df['col1'].nunique()

df['col1'].value_counts()

def times2(x):
 return 2*x

df['col2'].apply(times2)

df['col2'].apply(lambda x: x**2)